### ISSUE TITLE
Updated container breaks SchNet notebook

### ISSUE THREAD

**Issue by nmb-paperspace** [zzweig/pytorch-graphcore#7]
The updated container `graphcore/pytorch-jupyter:2.6.0-ubuntu-18.04-20220804` breaks the SchNet notebook because its frozen pip version of 21.3.1 can't see the required packages in `requirements-pyg.txt`:

```
%pip install -r requirements-pyg.txt

Looking in links: https://data.pyg.org/whl/torch-1.10.0+cpu.html
Collecting torch-scatter==2.0.9
  Using cached https://data.pyg.org/whl/torch-1.10.0%2Bcpu/torch_scatter-2.0.9-cp36-cp36m-linux_x86_64.whl (291 kB)
ERROR: Could not find a version that satisfies the requirement torch-sparse==0.6.13 (from versions: 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.1, 0.6.0, 0.6.1, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.6.10, 0.6.11, 0.6.12)
ERROR: No matching distribution found for torch-sparse==0.6.13
Note: you may need to restart the kernel to use updated packages.
```

The installs are required for the notebook to run.

**Comment by nmb-paperspace** [comment]
Removing the requirements that pip 21.3.1 can't see:

```
cat requirements-pyg.txt

# Install pre-built wheels for PyTorch Geometric that are compatible with
# poptorch
--find-links https://data.pyg.org/whl/torch-1.10.0+cpu.html

#torch-scatter==2.0.9
#torch-sparse==0.6.13
#torch-cluster==1.6.0
torch-spline-conv==1.2.1
#torch-geometric==2.0.4

# Visualisation packages
#matplotlib==3.5.2
periodictable==1.6.1
py3Dmol==1.8.0
```

and then installing them without versions specified gives mostly older versions, as expected

```
Collecting torch-scatter
  Downloading torch_scatter-2.0.9.tar.gz (21 kB)
...
Collecting torch-sparse
  Downloading torch_sparse-0.6.12.tar.gz (43 kB)
...
Collecting torch-cluster
  Downloading torch_cluster-1.5.9.tar.gz (38 kB)
...
Collecting torch-geometric
  Downloading torch_geometric-2.0.3.tar.gz (370 kB)
...
Collecting matplotlib
  Downloading matplotlib-3.3.4-cp36-cp36m-manylinux1_x86_64.whl (11.5 MB)
...

```

**Comment by nmb-paperspace** [comment]
The notebook after that appears to run anyway, but obviously it's not a great setup or set of code to show

**Comment by nmb-paperspace** [comment]
Notebook startup command `PIP_DISABLE_PIP_VERSION_CHECK=1` to `PIP_DISABLE_PIP_VERSION_CHECK=0` might allow latest pip again - try this.

**Comment by nmb-paperspace** [comment]
Doesn't work

**Comment by timbrown5** [comment]
I think the core issue is that the Ubuntu 18.04 containers ship with Python 3.6 - which is out of support. In your example above `torch-sparse==0.6.13` needs Python 3.7+ (see https://pypi.org/project/torch-sparse/0.6.13/).
I would suggest switching to the Ubuntu 20.04 containers, e.g. `graphcore/pytorch-jupyter:2.6.0-ubuntu-20.04-20220804`. Those have Python 3.8 and so shouldn't suffer from the above.

**Comment by denizb-graphcore** [comment]
Only TGN / TF1 models should use Ubuntu 18, all other images shall use Ubuntu 20 image.

**Comment by internetoftim** [comment]
Confirmed it runs on **graphcore/pytorch-jupyter:2.6.0-ubuntu-20.04-20220804**

**Comment by nmb-paperspace** [comment]
Also confirmed, so closing this one
